### PR TITLE
Add new ECwISC30to60E3r2 mesh

### PR DESCRIPTION
**Pull request by xylar**
See https://github.com/MPAS-Dev/compass/pull/689 for details on the mesh and E3SM initial condition.

### CODE REVIEW

**Comment by xylar** [comment]
@jonbob, this branch is ready for you to add mapping and domain files.

**Comment by xylar** [comment]
@jonbob, I assume the changes to `oRRS18to6v3` in your last commit aren't on purpose (maybe because you were working with a file from an older `master`)?  For now, they're not a big deal but just wanted to point them out so we don't accidentally merge them.

**Comment by xylar** [comment]
Ah, sorry about the datestamps!

**Comment by jonbob** [comment]
Passes:
SMS_P1440.ne30pg2_ECwISC30to60E3r2.WCYCL1850.anvil_intel
SMS_P1440.ne30pg2_r05_ECwISC30to60E3r2.WCYCL1850.anvil_intel

This could now be used for coupled model testing?

**Comment by xylar** [comment]
Closing in favor of https://github.com/E3SM-Project/E3SM/pull/5927

**Pull request closed without merging**
