### PR TITLE
Add Antarctic Ice Sheet meshes for MALI

### PR DESCRIPTION
**Pull request by matthewhoffman**
This PR introduces two new meshes of the Antarctic Ice Sheet for MALI:
* high res production mesh: mpas.ais4to20km
* low-res testing mesh: mpas.ais8to30km

### CODE REVIEW

**Comment by matthewhoffman** [comment]
@jonbob , I created this PR in progress for adding new Antarctic meshes.  I've added the mesh files to `/lcrc/group/acme/public_html/inputdata/glc/mpasli` and I have added the entries for the mapping files to `cime_config/config_grids.xml` but I left the entries blank until we get the mapping files made.  I'm happy to discuss how to proceed.

@xylar , should we add E3SM grid specs and mapping files for `oQU240wLI` (or create an oQU120wISC) for this PR too?

**Comment by xylar** [comment]
Yes to oQU240wLI. There's no appetite in the project for a new IcoswISC240 mesh.

**Comment by xylar** [comment]
Following up, it only makes sense to create mapping files for the 8 km AIS mesh to the oQU240wLI mesh, not the 4 km AIS.  This would just be for lightweight testing.

**Comment by xylar** [comment]
@matthewhoffman, do the new meshes also need to be added here?
https://github.com/E3SM-Project/E3SM/blob/a5273f081fd29c5d9a21a9d3e92f16618aaefab2/driver-mct/cime_config/config_component.xml#L1088
and here?
https://github.com/E3SM-Project/E3SM/blob/a5273f081fd29c5d9a21a9d3e92f16618aaefab2/driver-moab/cime_config/config_component.xml#L1088

**Comment by xylar** [comment]
Also presumably here:
https://github.com/E3SM-Project/E3SM/blob/a5273f081fd29c5d9a21a9d3e92f16618aaefab2/components/mpas-albany-landice/cime_config/buildnml#L85

**Comment by xylar** [comment]
Presumably, you just haven't got that far yet -- this is a work in progress, as you said.

**Comment by matthewhoffman** [comment]
@czender, @chloewhicker, and @stephenprice  , this PR will add our current AIS meshes and I'd like to add model_grid specifications and mapping files to support IG and BG cases with the firn model.  Can you confirm what land and atmosphere (data for IG or active for BG) grids you would want supported for that?

**Comment by czender** [comment]
@matthewhoffman We anticipate our immediate simulations all running on the LR trigrid mesh: r05 for land, and ne30pg2 for atmosphere.

**Comment by matthewhoffman** [comment]
Thanks, @czender.  So I think this spec covers your needs.   (there is a corresponding one for the second AIS MALI mesh as well)  Can you confirm?  Are you ok using the v3 `IcoswISC30E3r5` mask?  (I think that was already sorted in the GIS development push but just checking)

```
    <model_grid alias="ne30pg2_r05_IcoswISC30E3r5_ais8to30" compset="_MALI">
      <grid name="atm">ne30np4.pg2</grid>
      <grid name="lnd">r05</grid>
      <grid name="ocnice">IcoswISC30E3r5</grid>
      <grid name="rof">r05</grid>
      <grid name="glc">mpas.ais8to30km</grid>
      <grid name="wav">null</grid>
      <mask>IcoswISC30E3r5</mask>
    </model_grid>
```

**Comment by matthewhoffman** [comment]
Replaced by https://github.com/E3SM-Project/E3SM/pull/6440

**Pull request closed without merging**
