### PR TITLE
Update weights for btr subcycling in split-explicit solver

### PR DESCRIPTION
**Pull request by dengwirda**
This PR updates the default `gamma` weights (`config_btr_gam1_velWt1`, `config_btr_gam2_SSHWt1`) in the barotropic subcycling phase of the split-explicit solver. Based on work with @jeremy-lilly, @gcapodag  and @mark-petersen, a stability analysis of the linearised external mode problem was used to estimate the coefficients that improve the scheme's CFL-limit, while also reducing numerical dissipation. Overall, the new coefficients $\gamma_{1,2} = \frac{8}{15}$ allow larger time-steps to be used; approximately $\frac{4}{3}$ the length of the maximum stable step-size used with the current $\gamma_{1} = \frac{1}{2}$, $\gamma_{2} = 1$ pair. This allows, e.g. `config_btr_dt` to be increased from 60sec to 75sec for QU30km and EC60to30km meshes and overall runtime to be reduced.

Following Shchepetkin et al., the behaviour of a time-stepping scheme can be analysed using a dissipation-dispersion diagram, in which a 'perfect' integration scheme would reproduce the unit-circle exactly, stability requires the scheme to lie inside the circle, dissipative errors are represented by a reduced curve radius and dispersive errors by angular offset. 

Old weights:
old_btr_weights

New weights:
new_btr_weights

The current weights achieve $\mathrm{CFL_{max}} = 1.41$ and the new weights $\mathrm{CFL_{max}} = 1.88$, leading to the $\frac{4}{3}$ time-step extension.

Though there is a third weight `config_btr_gam3_velWt2` available, this is typically not used, with `config_btr_solve_SSH2 = .false.` Initial experiments did not suggest including this step improved either stability or accuracy (the opposite in fact), though additional investigation would be required on this front.

I've confirmed the new weights allow `config_btr_dt = 00:00:75` for QU30km and EC60to30km config.'s (vs the current 60 sec time-step) and that 3yr standalone spin-ups lead to eyeball-norm consistent (but non-BFB) output. Additional testing would be required to validate performance in coupled E3SM runs.

- Shchepetkin, A.F. and McWilliams, J.C., 2009. Computational kernel algorithms for fine-scale, multiprocess, longtime oceanic simulations. In Handbook of Numerical Analysis (Vol. 14, pp. 121-183).

### CODE REVIEW

**Comment by xylar** [comment]
@dengwirda, is this ready to review?  If so, who would you like to review it before it goes to E3SM?

**Comment by dengwirda** [comment]
@xylar, please feel free to weigh in re: reviews here --- this PR could e.g. be augmented to update `config_btr_dt` for E3SM config.'s, though validation on different meshes + G/B-cases would be required.

**Comment by jonbob** [comment]
@dengwirda - for this to also impact E3SM, you'll have to make the same change in 
````
~components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
````
which is where E3SM gets its default values from

**Comment by mark-petersen** [comment]
@dengwirda thanks for your analysis and proposed change. I agree with this change. The linear stability analysis indicates that it is better, as do your preliminary experiments. When we originally chose weights of 0.5, we did not conduct a thorough analysis of the best values.  This is potentially climate changing, so we would need to run a ten-year comparison simulation. 

We could make a PR into E3SM-Project with these changes, and get them into E3SM version 3 if the simulations look good. The tricky part is that the coupled group is already running long simulations to prepare for V3, so fundamental changes make it more difficult for them to compare their simulations this year.

**Comment by xylar** [comment]
> We could make a PR into E3SM-Project with these changes, and get them into E3SM version 3 if the simulations look good. The tricky part is that the coupled group is already running long simulations to prepare for V3, so fundamental changes make it more difficult for them to compare their simulations this year.

I would not take this too seriously in the sense that we are going to completely change the ocean and sea-ice meshes.  To me, this is going to be a much bigger disruption to the coupled group than the change proposed in this PR and I consider updating the meshes to be non-negotiable given how much work I have put into it so far.

**Review by mark-petersen — APPROVED** [review]
@dengwirda please go ahead and close this discussion PR, and make a PR into E3SM-Project for these changes. We can make the E3SM namelist changes there, and conduct further testing. Thanks!

**Comment by jonbob** [comment]
I ran a couple of 10-year EC30to60E2r2 G-cases to compare results using these new values with a baseline -- mpas-analysis output is at: [20230502.48test.anvil](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.jwolfe/20230502.48test.anvil/). As @dengwirda stated, the results pass the eyeball norm but are non-BFB. @dengwirda, should I run a third test with a longer config_btr_dt as well?

**Comment by dengwirda** [comment]
Thanks very much @jonbob, I'd expect that with `config_btr_gam1_velWt1, config_btr_gam2_SSHWt1 = 0.5333` the 60-to-30km config. should be able to run stably with `config_btr_dt = 75sec` (24 vs 30 subcycles), and it'd be great to confirm this with a G-case.

The btr time-step should (in theory) be mostly a function of the mesh + bathymetry (gravity wave speed), so I'd hope there's not a big feedback wrt. forcing.

I'll standalone spin-up the 30-to-10km config. next, and see whether a btr time-step extension is possible there too.

**Comment by jonbob** [comment]
I ran another test with 
````
 config_btr_dt = '0000_00:01:15'
 ````
and have mpas-analysis output comparing it with the previous test where
````
 config_btr_dt = '0000_00:01:00'
````
at [20230502.48test2.anvil](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.jwolfe/20230502.48test2.anvil/html/). Again it passes the eyeball norm but I did run cprnc on output files to confirm they were different. Throughput in the ocean went from about 15.4 to 16.3 sypd

**Comment by mark-petersen** [comment]
moved to https://github.com/E3SM-Project/E3SM/pull/6035

**Pull request closed without merging**
