### PR TITLE
Add new SOwISC12to30E3r2 ocean and sea-ice mesh

### PR DESCRIPTION
**Pull request by xylar**
Long name: SOwISC12to30kmL64E3SMv3r2

This version of the Southern Ocean Regionally Refined Mesh (SORRM) has resolution that is:
* 12 km around Antarctica
* 30 km elsewhere
It is intended to be similar to the IcoswISC30E3r5 mesh except in the Southern Ocean and around Antarctica.

This is a proposed E3SM v3 (E3) mesh for polar (formerly cryosphere) simulations.  This is revision 2 (r2) of the mesh, which includes a fix to the land-ice mask to remove land-locked sea-ice cells along ice-shelf calving fronts (https://github.com/MPAS-Dev/compass/pull/752).

The mesh was created using [compass](https://github.com/MPAS-Dev/compass), specifically this tag: https://github.com/MPAS-Dev/compass/releases/tag/mesh_SOwISC12to30E3r2

The mesh and the G-case results will be reviewed here:
https://acme-climate.atlassian.net/wiki/spaces/OO/pages/4059529268/Review+SOwISC12to30E3r2

A G- and B-case will begin shortly and analysis will be posted on the review page as soon as it is available.

### CODE REVIEW

**Comment by xylar** [comment]
@darincomeau and @jonbob, there is no real rush on this but I wanted to get the ball rolling.  This is a version of SORRM with a 30 km background resolution and the fix from https://github.com/MPAS-Dev/compass/pull/752.  It needs mapping files and all that stuff.

**Comment by xylar** [comment]
I just synced over the files to `/lcrc/group/e3sm/data/inputdata/`

**Comment by darincomeau** [comment]
Not sure if I should review here or at the E3SM one, but it looks like the next step is the 30 year G-case, presumably GMPAS-JRA-DIB-ISMF? I can get that started. The settings look good to me.

**Comment by xylar** [comment]
> GMPAS-JRA-DIB-ISMF

Presumably GMPAS-JRA-DIB-PISMF (not DISMF)?

But, yes, that sounds right to me.

**Comment by xylar** [comment]
> Not sure if I should review here or at the E3SM one

We can discuss here but the review should eventually be on E3SM.  (No E3SM PR for this yet.)

**Comment by darincomeau** [comment]
right, of course, on both counts. G-case in the queue on Anvil.

**Comment by xylar** [comment]
@darincomeau, can you help me get the CRYO1950 run working for this mesh?  I'm currently getting:
```
RROR: invalid value of use_case (1950_eam_CMIP6_chemUCI-Linoz-mam5-vbs) specified in commandline
```
when I try to set it up.

**Comment by darincomeau** [comment]
There's an open PR to fix the 1950 compsets, away from computer now so I
can't link it, buy check the main repo

**Comment by xylar** [comment]
Ah, great!  That's https://github.com/E3SM-Project/E3SM/pull/6053.  Open since November, so hopefully it gets in soon.

**Comment by xylar** [comment]
I'm closing this because we will move on to revision 3.

**Pull request closed without merging**
