### PR TITLE
Add ocean wetting-and-drying ramp feature

### PR DESCRIPTION
**Pull request by cbegeman**
This PR enhances the existing wetting-and-drying algorithm using an approach from O'Dea et al. 2020 (doi:10.1016/j.ocemod.2020.101708). Instead of zeroing out `normalVelocity` and `normalVelocity` tendencies in cells where the projected `layerThickness` drops below the user-defined minimum, this method ramps down the `normalVelocity` and its tendencies between a range of `layerThickness`es. 

[BFB][stealth]

### CODE REVIEW

**Comment by cbegeman** [comment]
This PR will be opened in E3SM after the clean-up W&D PR https://github.com/E3SM-Project/E3SM/pull/5418 is merged.

**Comment by cbegeman** [comment]
@sbrus89 demonstrated that the ramp feature improves the convergence of the W&D solution for the parabolic bowl test case. The relevant results for this PR are the "standard" lines:
image

I have also found that this feature is necessary to allow W&D in ice shelf cavities (specifically the wetting phase).

**Comment by cbegeman** [comment]
@sbrus89 Would you like to offer any review suggestions now or should I migrate this to E3SM?

**Review by sbrus89 — APPROVED** [review]
@cbegeman, this looks ready to move over to E3SM. Thanks for adding this feature!

**Comment by cbegeman** [comment]
Migrated to https://github.com/E3SM-Project/E3SM/pull/5590

**Pull request closed without merging**
