### PR TITLE
Update descriptions of dcEdge and dvEdge

### PR DESCRIPTION
**Pull request by xylar**
The existing descriptions were not clear to developers.

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen, @proteanplanet, @matthewhoffman, as representatives form each affected component, could you let me know if you're okay with these changes?
```
<var name="dvEdge" type="real" dimensions="nEdges" units="m"
    description="The great circle distance between vertices bordering a given edge.  It is the length of the edge on the primal mesh."
/>
<var name="dcEdge" type="real" dimensions="nEdges" units="m"
    description="The great circle distance between cell centers bordering a given edge.  It is the length of the edge on the dual mesh."
/>
```

**Comment by matthewhoffman** [comment]
@xylar , thanks for tackling this.  If we are adjusting these definitions, I would prefer some additional elaboration:

dvEdge:
The distance (great circle distance for spherical meshes, Euclidean distance for planar meshes) between the two vertices (defined by verticesOnEdge) located at the endpoints of a given edge.  It is the length of the edge on the primal mesh.

dcEdge
The distance (great circle distance for spherical meshes, Euclidean distance for planar meshes) between the centers of the two cells (defined by cellsOnEdge) neighboring a given edge.  It is the length of the edge on the primal mesh.

**Comment by xylar** [comment]
The second one should be "dual", rather than "primal", right?

**Comment by xylar** [comment]
Good point about planar vs. spherical.

**Comment by matthewhoffman** [comment]
> The second one should be "dual", rather than "primal", right?

Yes, oops, good catch.  Copy-and-paste error. :)

**Comment by xylar** [comment]
@matthewhoffman, could you take a careful look at the update I just made?  I want to make sure it's what you wanted.

**Comment by xylar** [comment]
Taking @mark-petersen off as he's away.

**Review by matthewhoffman — APPROVED** [review]
@xylar , I read it carefully out loud twice, and it looks good.

**Comment by xylar** [comment]
I need to update the respective E3SM namelist files using https://github.com/MPAS-Dev/MPAS-Tools/blob/master/source_code_processing/e3sm_namelist_file_generator/generate_e3sm_namelist_files.py

**Comment by xylar** [comment]
Never mind, there's nothing to update with `generate_e3sm_namelist_files.py`. Moving to E3SM...

**Comment by xylar** [comment]
Closing in favor of https://github.com/E3SM-Project/E3SM/pull/6427

**Pull request closed without merging**
