### PR TITLE
Fix some formatting in Registry for generating docs

### PR DESCRIPTION
**Pull request by xylar**
To generate Latex documentation from the Registry, we need to escape Latex in the namelist and variable descriptions.

### CODE REVIEW

**Comment by xylar** [comment]
Here is the PR where I'm proposing to update the User's Guide using these changes:
https://github.com/MPAS-Dev/MPAS-Documents/pull/77
As I mention there, the auto-generated documentation is constructed using the tool I updated here:
https://github.com/xylar/MPAS-Tools/blob/update-parse-registry/python_scripts/namelist_generation/parse_xml_registry.py

**Comment by xylar** [comment]
@mark-petersen, could you let me know if these changes look okay?  If so, I'll move over to E3SM.

**Review by mark-petersen — APPROVED** [review]
Yes, looks good. Thanks!

**Comment by xylar** [comment]
Thanks @mark-petersen!

Replaced by https://github.com/E3SM-Project/E3SM/pull/6293

**Pull request closed without merging**
