### PR TITLE
Disable land ice frazil salinity

### PR DESCRIPTION
**Pull request by cbegeman**
The option to have non-zero land ice frazil salinity was not fully supported. Here, we remove that option. This is BFB when land ice frazil salinity is zero, which has been the case in every configuration I am aware of.

This PR is to be merged after https://github.com/E3SM-Project/E3SM/pull/6229.

### CODE REVIEW

**Comment by cbegeman** [comment]
This PR has been tested on chrys, intel-impi with the IcosWISC compass standalone test.

**Comment by xylar** [comment]
@cbegeman, there are some more places that the namelist option needs to be removed:
https://github.com/E3SM-Ocean-Discussion/E3SM/blob/eb4d66bef46e65233d5a50c0c8e70866dd31fce4/components/mpas-ocean/bld/build-namelist#L762
https://github.com/E3SM-Ocean-Discussion/E3SM/blob/eb4d66bef46e65233d5a50c0c8e70866dd31fce4/components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml#L373
https://github.com/E3SM-Ocean-Discussion/E3SM/blob/eb4d66bef46e65233d5a50c0c8e70866dd31fce4/components/mpas-ocean/bld/namelist_files/namelist_definition_mpaso.xml#L1486-L1492
https://github.com/E3SM-Ocean-Discussion/E3SM/blob/eb4d66bef46e65233d5a50c0c8e70866dd31fce4/components/mpas-ocean/bld/build-namelist-section#L287
And the following needs to match `Registry`:
https://github.com/E3SM-Ocean-Discussion/E3SM/blob/eb4d66bef46e65233d5a50c0c8e70866dd31fce4/components/mpas-ocean/bld/namelist_files/namelist_definition_mpaso.xml#L1478-L1484

Once those are updated, I think this looks great and will be ready to go to E3SM!

**Comment by cbegeman** [comment]
@xylar Thanks for all the links! That made the fixup really easy! Changes here: https://github.com/E3SM-Ocean-Discussion/E3SM/pull/91/commits/4f3eeadd9f12e499ec0429fc8eec9c5cc214ec01

**Review by xylar — APPROVED** [review]

**Comment by darincomeau** [comment]
well that just made this a whole lot harder to review, I shouldn't have waited so long :D!

But I think with that last commit I agree this looks good. I can do a proper review on the real PR.

**Comment by xylar** [comment]
@darincomeau, it should be back to sanity...

**Comment by xylar** [comment]
@cbegeman, it sounds like this can move to E3SM, then.

**Comment by cbegeman** [comment]
Migrated to https://github.com/E3SM-Project/E3SM/pull/6397

**Pull request closed without merging**
