### PR TITLE
Wave Momentum Coupling between WW3-MPASO-EAM 

### PR DESCRIPTION
**Pull request by erinethomas**
NEW WAVE MOMENTUM COUPLING FEATURE
Full momentum coupling between WW3, MPAS-Ocean, and EAM is being implemented.
This discussion is for the purpose of getting a preliminary code review and feedback before an official PR is opened into E3SM.

A table summarizing all testing being performed is at the bottom of the page here:
https://acme-climate.atlassian.net/wiki/spaces/OO/pages/4271702034/2024.Q2+WAVEWATCH+III+maintenance+developments
Suggestions welcome for additional testing that is needed to open a PR into E3SM.

Git Repo:
https://github.com/E3SM-Project/E3SM/compare/master...erinethomas:E3SM:WaveMomentum

The use of WW3 is 'stealth' in that WW3 is NOT a standard component of E3SM for production runs. However, the implementation of wave-ocean-atm coupling in this PR defines the default coupling based upon the COMPSET used.
For example, a fully coupled base _with active waves_ (B compset + WW3) will assume full, two-way coupling between WW3-EAM-MPASO and MPAS-SI. (note: limited wave-ice coupling for now, full wave-ice coupling coming in near future). On the other hand, if a data atmosphere used, like in a G Case+WW3, EAM-WW3 coupling will default to "one-way" (data winds passed to WW3) while full two way coupling is used between the active components of WW3 and MPAS-O/MPAS-SI.

### CODE REVIEW

**Comment by erinethomas** [comment]
Feedback from @OlawaleClimate @sbrus89 @vanroekel @jonbob is especially appreciated.

**Comment by erinethomas** [comment]
@jonbob  - do I need to clean up this PR for a final version? The commit history is very messy since I rebased the code with "merges" from master....

**Comment by xylar** [comment]
@erinethomas, that would be my strong preference for what it's worth.  I prefer to avoid merge commits and to rebase instead whenever possible.

**Comment by erinethomas** [comment]
excellent - thanks for the fast response @xylar !

**Comment by erinethomas** [comment]
closing this PR for a "cleaned up" version

**Pull request closed without merging**
