### PR TITLE
Fix total land-ice freshwater flux in data mode

### PR DESCRIPTION
**Pull request by xylar**
Previously, the total was only being computed when thermodynamics below ice shelves are actively computed, whereas we need to compute the total of the interface flux and the frazil flux when the interface flux comes from a data file as well.  While we expect the frazil flux to be zero, these code modifications do not assume or require this to be true.

This PR addresses https://github.com/E3SM-Project/E3SM/issues/6719

### CODE REVIEW

**Comment by xylar** [comment]
Here is MPAS-Analysis from a 2-year G-case with DISMF:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis/20241029.GMPAS-JRA1p5-DIB-DISMF.TL319_IcoswISC30E3r5.fix_total_ismf.chrysalis/ocean/index.html

The total flux is no longer zero, as desired.

image

The variability in time is due to frazil, and shows that it can be pretty significant:

image

**Comment by xylar** [comment]
@darincomeau, anything you'd like to do to sanity-check this before it goes to E3SM?  Since it's BFB, I think my 2-year test should be sufficient.  But I could run a couple of B-case tests first to make sure it's really BFB as it should be.  If you're okay with it, I'd do that once we move to E3SM, though.

**Comment by xylar** [comment]
Also, do we need to add this to the BlueTip table?

**Comment by darincomeau** [comment]
Thanks @xylar for the fix here!

Do we know what happened where this functionality stopped working? In runs I had done earlier this year, DISMF was showing up as expected:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/E3SMv3/20240227.v3.LR.CRYO1850-DISMF.paolo.chrysalis/yrs151-200/ocean/index.html#antmelttime
image

**Comment by xylar** [comment]
@darincomeau, yes, @irenavankova figured out in her work that we were missing frazil in the total land-ice melt flux.  She fixed that in E3SM in:
https://github.com/E3SM-Project/E3SM/pull/6300
and I fixed it in MPAS-Analysis in:
https://github.com/MPAS-Dev/MPAS-Analysis/pull/989

I think we assumed that frazil would simply be disabled in cases with DISMF and didn't include it in the total but I think this approach is better.  If frazil is disabled, the total is simply the same as the interface value and no special conditions are needed for plotting in MPAS-Anslysis.

**Comment by darincomeau** [comment]
@xylar thanks for the fix! agree we can move this over to main repo. BFB tests against baselines with `cryo_developer_suite` should cover it?

**Comment by darincomeau** [comment]
and yes we'll add this PR alongside the scaledDISMF PR in the SORRMv3 development table

**Comment by xylar** [comment]
Closed in favor of https://github.com/E3SM-Project/E3SM/pull/6729

**Pull request closed without merging**
