### PR TITLE
Update modules for chicoma-cpu

### PR DESCRIPTION
**Pull request by xylar**
Several modules are no longer available after a recent machine upgrade.

### CODE REVIEW

**Comment by xylar** [comment]
@jonbob and @stephenprice, I think we might want to update the Chicoma modules.  I have suggestions here, but haven't tested them yet.  I wanted to check with you both before putting time into this.

**Comment by xylar** [comment]
## Testing

`SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chicoma-cpu_gnu` passed.

Still working on `SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.chicoma-cpu_intel`.

**Comment by xylar** [comment]
@jonbob and @stephenprice, can you let me know if this is useful to you in the near term, and if you can do some tests if so?  This isn't urgent but it would be nice if it doesn't get forgotten.

**Comment by jonbob** [comment]
@xylar - let's move this PR to e3sm? It will get more visibility and apparently chicoma is broken without it

**Comment by xylar** [comment]
Closed in favor of https://github.com/E3SM-Project/E3SM/pull/5986

**Pull request closed without merging**
