### PR TITLE
Add new SOwISC12to30E3r3 ocean and sea-ice mesh

### PR DESCRIPTION
**Pull request by xylar**
Long name: SOwISC12to30kmL80E3SMv3r3

This version of the Southern Ocean Regionally Refined Mesh (SORRM) has resolution that is:
* 12 km around Antarctica
* 30 km elsewhere
It is intended to be similar to the IcoswISC30E3r5 mesh except in the Southern Ocean and around Antarctica.

This is a proposed E3SM v3 (E3) mesh for polar (formerly cryosphere) simulations.  This is revision 3 (r3) of the mesh, which includes many changes from revision 2 outlined in https://github.com/MPAS-Dev/compass/pull/807.  The mesh will be tagged as: https://github.com/MPAS-Dev/compass/releases/tag/mesh_SOwISC12to30E3r3 if it is accepted.

The mesh and the G-case results will be reviewed here:
https://acme-climate.atlassian.net/wiki/spaces/OO/pages/4441145345/Review+SOwISC12to30E3r3

A G- and B-case will begin shortly and analysis will be posted on the review page as soon as it is available.

### CODE REVIEW

**Comment by xylar** [comment]
@jonbob and @darincomeau, the mesh is ready for some sanity checking and then making mapping files.

**Comment by xylar** [comment]
@jonbob, apologies!  @cbegeman asked me to make some changes to the mesh (to ensure a thicker minimum water-column thickness).  I don't think those changes will affect the horizontal mesh but I am not sure that they won't.  Even if the cell count with these changes happens to be the same, the cell order might be different.

So if you happen to have started making mapping files, I'm afraid you'll need to start over.  If you haven't had a chance to start yet, that would be a relief!

**Comment by xylar** [comment]
@jonbob, okay, @cbegeman has signed off on the water-column thickness with the latest version of this mesh and I have just updated the files in `/lcrc/group/e3sm/data/inputdata/`.  I think we're ready for mapping files from the new version of the mesh/initial condition.

**Comment by jonbob** [comment]
Are you all interested in any particular configurations? I've made mapping files for the following atm resolutions:
T62
TL319
ne30pg2
ne120pg2
and r05 plus r025 if you want to run trigrid. I also made runoff mapping files for:
rx1
r05
r025
JRA025

**Comment by darincomeau** [comment]
That looks complete to me - thanks @jonbob !

**Comment by xylar** [comment]
I believe we're most interested in B-cases with the r05 try grid.  We will probably use the JRA grid, too.  But it's really good to have all those options.  Thanks @jonbob!

**Comment by darincomeau** [comment]
If we don't want to stage them all now, I agree with @xylar that `ne30pg2_r05_SOwISC12to30E3r3` and `TL319_SOwISC12to30E3r3` (with JRA025 runoff map) are the ones we'll want first for testing.

**Comment by jonbob** [comment]
I added support for G-case with T62 and TL319 configurations, as well as fully-coupled using ne30pg2 in both bi- and tri-grid. I've staged the necessary files on the local lcrc inputdata directory, and tested:
````
SMS.ne30pg2_r05_SOwISC12to30E3r3.WCYCL1850NS.chrysalis_intel
SMS.TL319_SOwISC12to30E3r3.GMPAS-JRA1p5.chrysalis_intel
````
So it's ready for your testing. Please note I didn't make spunup IC files from a G-case for use in B-cases

**Comment by xylar** [comment]
@jonbob, oh, dear.  @darincomeau already found a problem with the horizontal mesh (a place where we need a critical passage to keep there from being a hole in the land ice).  I have finally fixed the issue after 2 false starts.  I am rebuilding all the SORRM r3 files now.  I will likely ping you tomorrow to make new mapping files (again!).  I'm very sorry about that.

**Comment by jonbob** [comment]
@xylar -- no problem. Darin had warned me yesterday, so I didn't push more on it. And I always need the practice making mapping files!

**Comment by xylar** [comment]
> And I always need the practice making mapping files!

Oh, I doubt that!  I bet you could make them in your sleep at this point.

**Comment by xylar** [comment]
@darincomeau, if you happen to be working today, could you give the new version of the mesh a sanity check before @jonbob makes mapping files.  I really want the 3rd time to be the charm here...

**Comment by darincomeau** [comment]
sorrme3r3_ap
sorrme3r3_ap_zoom
 @xylar looks good to me! I checked around the coast again and didn't see any other issues.

**Comment by xylar** [comment]
Thanks @darincomeau!!

**Comment by jonbob** [comment]
I updated the mapping and domain files, and pushed the new file datestamps and mesh size to this PR. I have staged the files in the lcrc local inputdata directory for testing. I did successfully make the following cases:
* SMS_P640.TL319_SOwISC12to30E3r3.GMPAS-JRA1p5.chrysalis_intel
* SMS_P1280.ne30pg2_r05_SOwISC12to30E3r3.WCYCL1850NS.chrysalis_intel
but they are still in the queue.

**Comment by xylar** [comment]
Thanks so much @jonbob!  I just updated the `inputdata` files from Compass with the fix that I mentioned in the Polar call yesterday.

I'll rerun the 2 smoke tests you ran to make sure things are still fine, but I expect them to be.

**Comment by xylar** [comment]
Yep, both tests passed for me:
```
SMS_P640.TL319_SOwISC12to30E3r3.GMPAS-JRA1p5.chrysalis_intel
SMS_P1280.ne30pg2_r05_SOwISC12to30E3r3.WCYCL1850NS.chrysalis_intel
```

**Comment by darincomeau** [comment]
Ok great, I'll get the G-case going

**Comment by jonbob** [comment]
Just fyi. I did make mapping files to support ne120_r025_SOwISC12to30E3r3 as well. Please let me know if you want to add this configuration to the PR

**Comment by xylar** [comment]
@jonbob, if you've bothered to make the mapping files, I think it makes sense to add the configuration here as well.

**Comment by xylar** [comment]
@darincomeau, thanks for adding the B-case initial conditions!

Keep us posted on how the G-cases go.

**Comment by darincomeau** [comment]
>Keep us posted on how the G-case goes.

Looks like it'll still be in the queue for awhile.

I also have a B-case sitting in the queue. It's a `CRYO1850` compset, not `CRYO1950`, because there isn't an `fsurdat` file for 1950 conditions on the `r05` grid (which we should probably ask for).

**Comment by xylar** [comment]
@darincomeau, do you know who to ask?  We do probably want that.

**Comment by darincomeau** [comment]
I think Wuyin?

**Comment by xylar** [comment]
@darincomeau, please stop any SORRM r3 simulations you're doing, as @proteanplanet discovered ongoing problems in https://acme-climate.atlassian.net/wiki/spaces/OO/pages/4441145345/Review+SOwISC12to30E3r3

I am generating a new version of the mesh and initial condition.

@jonbob, I'm afraid this seems to have led to 4 additional cells being masked as land ice so new mapping files will be needed once again.

Sorry!!

**Comment by jonbob** [comment]
Updated the mapping and domain files. They're staged and I've submitted B- and G-case tests

**Comment by xylar** [comment]
Thanks @jonbob!  That's really helpful!

**Comment by darincomeau** [comment]
We're seeing the G-case crash in the third or fourth month in sea ice; at first I tried increasing dynamics subcycling to 2, 3, which would only allow the run to get a short time further. The most recent crash I have was in `0001-04-27_21:30:00`, where I started looking at the fields in the sea ice abort file.

There's a few isolated cells on the eastern side of the peninsula that are accumulating up to 8m of ice, about a month into austral growth conditions, starting from no ice:

abort_ice_volume

Here's the zonal velocity (I'm pretty sure, `uVelocityGeo`), so I think this says ice is being advected westward to the problem cell(s), highly localized in opposite sign of prevailing motion:
abort_uvelocity

The sea ice concentration field shows very high concentration of (thin) ice:
abort_ice_area

I'm not sure what to make of this, but I'm pretty sure this is what's causing the crash.

**Comment by xylar** [comment]
@darincomeau, can you show the `landIceFreshwaterFlux` in the same problem cell (and maybe other things like `ssh`, `bottomDepth`, `landIceFloatingFraction`?  It looks like this is a location where ssh might be depressed by about 100 m and `landIceFloatingFraciton` might be around 0.5.  In previous meshes, I have cut `landIceFloatingFraction` off if it's less than 0.5 but this means losing fluxes and has consequences for conservation.  However, if land-ice melt in sea-ice cells causes trouble, this is important to know.

I'm away for about 10 days, so I would appreciate as much debugging of the issue as you (and others) can do until I get back.  We really need to make progress on this mesh because it's holding up not only Polar but also FAnSSIE work.

**Comment by xylar** [comment]
We compute the ssh gradient as seen by the sea-ice model by first removing `landIceDraft` from `ssh`.  This could be a location where ssh has changed too much from `landIceDraft` and the difference between the two is driving sea ice up against the continent.  Could someone look into that?

**Comment by cbegeman** [comment]
@darincomeau and @xylar: Some things that I noticed while examining a particular sea ice cell at -73.082,300.015 with 42m of sea ice thickness at the time of the crash:

* sea ice divergence ~1000 %/day
* land ice fraction is 0.48, thus NOT allowed to have land ice thermodynamics
* land ice draft is -102m, pressure-adjusted SSH is -1m
* Water column is close to freezing point; for the month before the crash the main freshwater flux into the cell is from icebergs (2e-6 kg m^-2 s^-1) which is roughly equal to the amount of sea ice frazil formation (this is what @proteanplanet has been calling the salty iceberg phenomenon)
* sea ice tendency due to transport >> tendency due to thermodynamics

**Comment by cbegeman** [comment]
> We compute the ssh gradient as seen by the sea-ice model by first removing landIceDraft from ssh. This could be a location where ssh has changed too much from landIceDraft and the difference between the two is driving sea ice up against the continent. Could someone look into that?

@xylar landIceDraft - ssh = 6m, consistent with ~1m depression from atm and ~5m depression from sea ice.

**Comment by xylar** [comment]
> land ice fraction is 0.48, thus NOT allowed to have land ice thermodynamics

I could be wrong but I don't believe that is correct. That was the practice before this mesh version but I wanted to try to not cut off melt in this version to have better conservation.

**Comment by cbegeman** [comment]
@xylar Whether melt is present is determined by `landIceFloatingFraction`, and that's zero, so it is off in this cell.

**Comment by darincomeau** [comment]
@cbegeman thanks for the much better job at debugging!

**Comment by proteanplanet** [comment]
All - I've read this thread now back from leave.  Is there anything I need to contribute at the present time?

**Comment by cbegeman** [comment]
@proteanplanet Thanks for checking in! I'm seeing suspiciously high layer slopes (haney numbers) around the cell that crashes so I think we may want to explore more bathymetry and land ice draft smoothing when @xylar returns from vacation.

**Comment by xylar** [comment]
I believe I have a likely culprit but not yet a good solution.

In an effort to move toward the approach we plan to use for MALI coupling, I switched from interpolating bathymetry exclusively from areas of floating ice and open ocean to all areas (including grounded ice) where the bed is below sea level.  It appears that many cells that include large fractions of grounded ice (bordering on the 50% cutoff) also often have quite different land-ice draft than their neighbors.  In the process of SSH adjustment, the SSH used in the model accumulates differences of up to ~150 m from the ice draft in some locations.  Many of these locations are away from the open ocean, so likely unproblematic.  Near the problem cell, the difference is ~50 m, and this will appear in the SSH gradient seen by sea ice at the neighboring, problem cell.

ssh_minus_draft

One obvious solution to this problem would be to use the SSH after adjustment as the new ice draft.  But a new problem emerges: such an approach doesn't accommodate changing ice topography in the future.  We do not have a way to update this new definition of the ice draft with time as the ice evolves.

**Comment by xylar** [comment]
The simplest solution I have come up with for this problem would be just to set `gradSSH` to zero for edges adjacent to cells where the `landIceFraction > 0`.  I don't think we really trust the sea-surface tilt (for use in the sea ice model) in locations where the surface is being depressed by land ice.  We don't have a good way to say what the sea surface would have been if the land-ice pressure weren't pushing it down.

At first, I thought that an approach using `effectiveDensity` might be a solution.  But I realized that that approach would probably result in values of `pressureAdjustedSSH` that are zero where `landIceFraction > 0` by construction, which seems worse than having the *gradient* of `pressureAdjustedSSH` be zero in these locations.  Any approach I could come up with to correct this seemed effectively equivalent to assuming `gradSSH == 0` as in the simple approach above.

**Comment by xylar** [comment]
Here is my implementation of the proposed solution, which I have asked @darincomeau to try out:
https://github.com/xylar/E3SM/commit/cadb96620c880e733e303785e90b4e11c39bb20a

**Comment by proteanplanet** [comment]
Is the problem that we are coupling through scalar grid points?  Where on grid cells is gradSSH being set to zero in your approach? Is it just at the ice shelf boundary wall of each grid cell?

**Comment by xylar** [comment]
@proteanplanet, we would be setting the ssh gradient to zero on any edges that have a neighboring cells with nonzero `landIcePressure` (and `landIceDraft` and `landIceFraction`).  This would include open ocean cells, since we have nonzero `landIcePressure` even beyond the calving front as defined by `landIceMask`.

**Comment by xylar** [comment]
@cbegeman is interested in thinking through an alternative approach that tries to extrapolate the ssh gradient to cells with nonzero `landIcePressure`, but in our Slack discussion, this seemed like it might be complicated and require a design doc.

**Comment by proteanplanet** [comment]
Is it possible to include only the ssh gradient due to atmospheric and sea ice pressure?  Switching it off entirely will impact geostrophic flow that is fundamental near polynyas and for the east wind drift.

**Comment by cbegeman** [comment]
@proteanplanet I think the best way to do this is to do a reconstruction of the SSH gradient field using only the edges that are not adjacent to land ice, as @xylar was alluding to, rather than zeroing out the SSH gradient in the whole cell adjacent to land ice. But I'm open to other ideas if you have them!

**Comment by proteanplanet** [comment]
There's a lot here I'm not understanding.  Please can we meet tomorrow for a sprint to explain your plans?

**Comment by xylar** [comment]
> Is it possible to include only the ssh gradient due to atmospheric and sea ice pressure? 


No, not really. The SSH is determined by ocean dynamics and can't be broken into individual contributions so easily. We can certainly chat about this more. I am increasing concerned that the correct solution may be rather complicated.

**Comment by proteanplanet** [comment]
OK. Perhaps instead of applying a Dirichlet boundary condition on the sea ice model (SSH is identical at the boundary as for one grid point in, hence gradSSH=0, we could apply Neumann boundary condition, where gradSSH is identical at the boundary as the unaffected cell inside the boundary. By boundary, I mean cells with nonzero landIcePressure.  I think that would work for sea ice and is more justifiable in publications.

**Comment by xylar** [comment]
@proteanplanet, that sounds fine to me. If I understand, this would be the same as extrapolating gradSSH instead of just pressureAdjustedSSH. I don't know off the top of my head how we might accomplish this in practice since extrapolating a scalar is a ton easier than extrapolating a vector in MPAS.

**Comment by cbegeman** [comment]
> > OK. Perhaps instead of applying a Dirichlet boundary condition on the sea ice model (SSH is identical at the boundary as for one grid point in, hence gradSSH=0), we could apply a Neumann boundary condition, where gradSSH is identical at the boundary as the unaffected cell inside the boundary. By boundary, I mean cells with nonzero landIcePressure. I think that would work for sea ice and is more justifiable in publications.
> 
> @proteanplanet, that sounds fine to me. If I understand, this would be the same as extrapolating gradSSH instead of just pressureAdjustedSSH. I don't know off the top of my head how we might accomplish this in practice since extrapolating a scalar is a ton easier than extrapolating a vector in MPAS.

@xylar I don't understand what you mean because `pressureAdjustedSSH` is not extrapolated as far as I can tell. What @proteanplanet's proposing seems similar to the idea of excluding the land ice boundary edges' `gradSSH(iEdge)` from the reconstruction. But were you thinking we would do something more manual and take `gradSSH` from nearby edges and extrapolate and rotate it onto a land ice boundary edge before the reconstruction?

**Comment by xylar** [comment]
@cbegeman, my idea of setting `gradSSH` to zero is equivalent to extrapolating SSH into the land-ice region as far as I can tell.

I don't think we have a plausible method for reconstruction gradSSH at cell centers from a subset of edges, so we would need to create a value for gradSSH at all edges (including those bounded by land ice on one side and maybe even including open-ocean edges bounded on both sides by some fraction of land ice).  I don't think there are any tricks we can use with the existing, very local vector reconstruction that would take care of this without some form of extrapolation of pressureAdjustedSSH or gradSSH.

**Comment by xylar** [comment]
I discovered that I made a mistake in masking the ice sheet thickness in the data set that combines GEBCO and BedMachine.  This data set is so large that I can't visualize it in ParaView, which has sometimes made sanity checking tricky.  Even so, it should have been immediately apparent that the ice sheet thickness after remapping was not correct:
ice_sheet_thick

I believe this issue is likely propagating the strange results in SSH adjustment that we are seeing and then to the sea ice problem.    My hope is that once I solve this issue, we can retest without any additional fiddling with `landIceDraft`, `pressureAdjustedSSH` or `gradSSH`.

**Comment by xylar** [comment]
Here is the same field as above after fixing this in compass:

**Comment by xylar** [comment]
I'm still seeing big changes between `ssh` (after adjustment) and `landIceDraft` (before adjustment)

land_ice_draft_minus_ssh

**Comment by xylar** [comment]
Here is the ice sheet thickness using the latest approach, which doesn't allow it to exceed the flotation thickness:
limited_thickness

The ice draft and pressure are similarly limited (as they are just scaled versions of the same field).

**Comment by xylar** [comment]
After SSH adjustment, everything now looks sensible, with smooth changes that are less than 4 m:
ssh_minus_land_ice_draft

**Comment by darincomeau** [comment]
Mesh review tests underway:

G-case:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/20240829.GMPAS-JRA1p5-DIB-PISMF.TL319_SOwISC12to30E3r3.mesh-review-test.chrysalis/

B-case:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/E3SMv3_dev/v3.SORRME3r3.piControl/

**Comment by proteanplanet** [comment]
@xylar Would it help me for to review the mesh once more with my script?  I can set it running this morning.

**Comment by xylar** [comment]
@proteanplanet, yes, I think it wouldn't hurt to rerun your script.  I don't *think* much has changed but I also absolutely don't want to assume that.

**Comment by xylar** [comment]
@jonbob, let me know if this mesh is ready to go to E3SM from your perspective.

**Comment by darincomeau** [comment]
I think @proteanplanet was about ready to sign off on this. We'd like to get it in for the new tag if possible.

**Comment by xylar** [comment]
Closed in favor of https://github.com/E3SM-Project/E3SM/pull/6631

**Comment by darincomeau** [comment]
>We'd like to get it in for the new tag if possible.

Rescinding this statement, not a priority for 3.0.1

**Pull request closed without merging**
