### PR TITLE
Mask time series stats variables

### PR DESCRIPTION
**Pull request by cbegeman**
This PR builds on https://github.com/E3SM-Project/E3SM/pull/5154 and https://github.com/E3SM-Project/E3SM/pull/5251 and applies fill value masking to non-restart time series stats streams. It also specifies the masking array for a subset of variables in the Registry.

### CODE REVIEW

**Comment by cbegeman** [comment]
I found that the `activeTracer*Tendency` variables could not be masked without introducing non-BFB changes in the `mixedLayerHeatBudget` analysis member stream for the `QU240/PHC/analysis_test` test case.

**Comment by cbegeman** [comment]
This PR results in the expected fill value masking for the `CMPASO-TL319_EC30to60E2r2` test on chrysalis. It is also BFB with master using the compass ocean PR test suite.

**Comment by cbegeman** [comment]
@xylar Could you bring E3SM-Ocean-Discussion/master up to date with E3SM/master? Thanks!

**Comment by xylar** [comment]
@cbegeman, done!

**Comment by xylar** [comment]
> I found that the activeTracer*Tendency variables could not be masked without introducing non-BFB changes in the mixedLayerHeatBudget analysis member stream for the QU240/PHC/analysis_test test case.

I think it's okay not to mask there fields.  Hopefully, they're zero where they're invalid.  It is a bit mystifying, though.  It might be worth finding out why (in the long run, not for this PR).

**Comment by cbegeman** [comment]
> I found that the activeTracer*Tendency variables could not be masked without introducing non-BFB changes in the mixedLayerHeatBudget analysis member stream for the QU240/PHC/analysis_test test case.

> I think it's okay not to mask there fields. Hopefully, they're zero where they're invalid. It is a bit mystifying, though. It might be worth finding out why (in the long run, not for this PR).

@xylar Sounds good. Those fields are not masked in this PR.

**Comment by xylar** [comment]
> Those fields are not masked in this PR.

Yes, that's what I gathered, though I didn't check myself.

**Comment by xylar** [comment]
@cbegeman, this looks great and passed both PR and `SMS_Ld3.T62_oQU120.CMPASO-IAF.chrysalis_intel` tests.  Please move it over to E3SM when you're ready.

**Comment by cbegeman** [comment]
@xylar Thank you so much for testing! Will do

**Comment by cbegeman** [comment]
Migrated to https://github.com/E3SM-Project/E3SM/pull/5325

**Pull request closed without merging**
